### ISSUE TITLE
M2.2.2 Ошибка 500 для /rest/default/V1/carts/mine/shipping-information

### ISSUE THREAD

**Issue by gamul** [bxn5/magegain-novaposhta#17]
M2.2.2
В родном чекауте выглядит вот так: https://www.screencast.com/t/ehKHqxFf6 - нет выбора отделений. При переключении на адресную доставку - выглядит так же.

В onestepcheckout (Aheadworks OneStepCheckout) поле "Отделение новой почты" не отображается. После выбора любого из способов доставки (отделение или адрес) вылазят ошибки:

Ошибка 500 для /rest/default/V1/carts/mine/shipping-information https://www.screencast.com/t/FYreWaTOm5a
В var\report\api\

`"Fatal Error: 'Uncaught Error: Call to a member function getCarrierDepartment() on null in D:\\Winginx\\home\\mysite.local\\public_html\\app\\code\\Magegain\\Novaposhta\\Model\\Quote\\AddressPlugin.php:19\nStack trace:\n#0 D:\\Winginx\\home\\mysite.local\\public_html\\vendor\\magento\\framework\\Interception\\Interceptor.php(121): Magegain\\Novaposhta\\Model\\Quote\\AddressPlugin->beforeSaveAddressInformation(Object(Magento\\Checkout\\Model\\ShippingInformationManagement\\Interceptor), 17, Object(Magento\\Checkout\\Model\\ShippingInformation))\n#1 D:\\Winginx\\home\\mysite.local\\public_html\\vendor\\magento\\framework\\Interception\\Interceptor.php(153): Magento\\Checkout\\Model\\ShippingInformationManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}(17, Object(Magento\\Checkout\\Model\\ShippingInformation))\n#2 D:\\Winginx\\home\\mysite.local\\public_html\\generated\\code\\Magento\\Checkout\\Model\\ShippingInformationManagement\\Interceptor.php(26): Magento\\Checkout\\Model\\ShippingInformationManagement\\Interceptor->___callPlugins('saveAddressInfo...', Array, Array)\n#3 [i' in 'D:\\Winginx\\home\\mysite.local\\public_html\\app\\code\\Magegain\\Novaposhta\\Model\\Quote\\AddressPlugin.php' on line 19"`

**Comment by bigshusha** [comment]
Как у Вас получилось вообще чтоб появился способ доставки НП на 2.2.2. Я как не воюю, нет его. Чистая установка, обновлены таблицы городов и складов.

**Comment by 4developer** [comment]
> Как у Вас получилось вообще чтоб появился способ доставки НП на 2.2.2. Я как не воюю, нет его. Чистая установка, обновлены таблицы городов и складов.

Я не специалист в мадженто но удалите  <item name="provider" xsi:type="string">city.city_listing_data_source</item>
из checkout_index_index.xml все заработает.   Почему? это уже к специалистам)) Может кто то объяснит для чего эта строка
